# Generated by Django 4.1.6 on 2023-02-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('location', models.TextField(max_length=500)),
                ('type', models.IntegerField(choices=[(0, '')])),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
