# Generated by Django 4.1.6 on 2023-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_incidentmodel_image_alter_incidentmodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmodel',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Road Accidents'), (1, 'Domestic Accidents'), (2, 'Industrial Accidents')], null=True),
        ),
    ]
