# Generated by Django 4.1.6 on 2023-04-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_incidentmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
