# Generated by Django 4.1.6 on 2023-05-05 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_incidentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentmodel',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Road Accident'), (1, 'Domestic Accident'), (2, 'Industrial Accident')], null=True),
        ),
    ]
