# Generated by Django 4.1.6 on 2023-05-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_incidentmodel_user_alter_incidentmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmodel',
            name='victim',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='AssignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Police'), (1, 'Ambulance'), (2, 'Fire brigade'), (3, 'Other')], null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.incidentmodel')),
            ],
        ),
    ]
